/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHomeErc20ToNativeBridge,
  IHomeErc20ToNativeBridgeInterface,
} from "../../../../contracts/helpers/Erc20ToNativeBridgeHelper.sol/IHomeErc20ToNativeBridge";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "_message",
        type: "bytes32",
      },
    ],
    name: "numMessagesSigned",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_hash",
        type: "bytes32",
      },
      {
        name: "_index",
        type: "uint256",
      },
    ],
    name: "signature",
    outputs: [
      {
        name: "",
        type: "bytes",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_hash",
        type: "bytes32",
      },
    ],
    name: "message",
    outputs: [
      {
        name: "",
        type: "bytes",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_number",
        type: "uint256",
      },
    ],
    name: "isAlreadyProcessed",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IHomeErc20ToNativeBridge__factory {
  static readonly abi = _abi;
  static createInterface(): IHomeErc20ToNativeBridgeInterface {
    return new Interface(_abi) as IHomeErc20ToNativeBridgeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHomeErc20ToNativeBridge {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IHomeErc20ToNativeBridge;
  }
}
