services:
  postgres-bridge-indexer:
    container_name: postgres-bridge-indexer
    image: postgres:16
    shm_size: 16g
    command: postgres -c 'max_connections=500' -c work_mem=256MB -c maintenance_work_mem=256MB -c max_wal_size=1GB
    ports:
      - 4123:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - bridge-indexer
    environment:
      - POSTGRES_DB=bridge-indexer
      - POSTGRES_USER=bridge-indexer
      - POSTGRES_PASSWORD=password

networks:
  bridge-indexer:
    driver: bridge

volumes:
  bridge-indexer:
    external: true
