services:
  postgres-bridge-indexer:
    container_name: postgres-bridge-indexer
    image: postgres:16
    shm_size: 16g
    command: postgres -c 'max_connections=500' -c work_mem=256MB -c maintenance_work_mem=256MB -c max_wal_size=1GB
    ports:
      - 4123:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - bridge-indexer
    environment:
      - POSTGRES_DB=bridge-indexer
      - POSTGRES_USER=bridge-indexer
      - POSTGRES_PASSWORD=password

  bridge-indexer:
    container_name: bridge-indexer
    image: bridge-indexer
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bridge-indexer
    command: bun run start
    ports:
      - 42069:42069
    deploy:
      resources:
        limits:
          memory: 8G
    volumes:
      - ./abis:/app/abis
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - ./bun.lockb:/app/bun.lockb
      - ./ponder.config.ts:/app/ponder.config.ts
      - ./ponder.schema.ts:/app/ponder.schema.ts
      - ./ponder-env.d.ts:/app/ponder-env.d.ts
    environment:
      - NODE_OPTIONS="--max-old-space-size=8192"
      - DATABASE_URL=postgresql://bridge-indexer:password@postgres-bridge-indexer:5432/bridge-indexer

networks:
  bridge-indexer:
    driver: bridge

volumes:
  bridge-indexer:
    external: true
