import { createSchema } from '@ponder/core'

export default createSchema((t) => ({
  Block: t.createTable(
    {
      id: t.hex(),
      chainId: t.bigint(),
      hash: t.hex(),
      number: t.bigint(),
      timestamp: t.bigint(),
      baseFeePerGas: t.bigint(),
      transactions: t.many('Transaction.blockId'),
      userRequestForSignature: t.many('UserRequestForSignature.blockId'),
      userRequestForAffirmation: t.many('UserRequestForAffirmation.blockId'),
      signedForUserRequest: t.many('SignedForUserRequest.blockId'),
      signedForAffirmation: t.many('SignedForAffirmation.blockId'),
      affirmationComplete: t.many('AffirmationComplete.blockId'),
      relayMessage: t.many('RelayMessage.blockId'),
    },
    {
      hash: t.index('hash'),
      number: t.index('number'),
    },
  ),
  Transaction: t.createTable(
    {
      id: t.hex(),
      blockId: t.hex().references('Block.id'),
      block: t.one('blockId'),
      hash: t.hex(),
      index: t.bigint(),
      from: t.hex(),
      to: t.hex(),
      value: t.bigint(),
      maxFeePerGas: t.bigint().optional(),
      maxPriorityFeePerGas: t.bigint().optional(),
      gas: t.bigint(),
      gasPrice: t.bigint().optional(),
      nonce: t.bigint(),
      userRequestForSignature: t.many('UserRequestForSignature.transactionId'),
      userRequestForAffirmation: t.many(
        'UserRequestForAffirmation.transactionId',
      ),
      signedForUserRequest: t.many('SignedForUserRequest.transactionId'),
      signedForAffirmation: t.many('SignedForAffirmation.transactionId'),
      affirmationComplete: t.many('AffirmationComplete.transactionId'),
      relayMessage: t.many('RelayMessage.transactionId'),
    },
    {
      blockId: t.index('blockId'),
      hash: t.index('hash'),
      from: t.index('from'),
      to: t.index('to'),
      maxFeePerGas: t.index('maxFeePerGas'),
      maxPriorityFeePerGas: t.index('maxPriorityFeePerGas'),
      gasPrice: t.index('gasPrice'),
      gas: t.index('gas'),
      nonce: t.index('nonce'),
    },
  ),
  LatestValidatorStatusUpdate: t.createTable(
    {
      id: t.hex(), // bridge id + address
      orderId: t.hex().references('ValidatorStatusUpdate.id'),
      order: t.one('orderId'),
      bridgeId: t.hex().references('BridgeSide.id'),
      bridge: t.one('bridgeId'),
    },
    {
      orderId: t.index('orderId'),
      bridgeId: t.index('bridgeId'),
    },
  ),
  ValidatorStatusUpdate: t.createTable(
    {
      id: t.hex(), // orderId
      validatorId: t.hex(),
      address: t.hex(),
      active: t.boolean(),
      logIndex: t.int(),
      blockId: t.hex().references('Block.id'),
      block: t.one('blockId'),
      transactionId: t.hex().references('Transaction.id'),
      transaction: t.one('transactionId'),
      bridgeId: t.hex().references('BridgeSide.id'),
      bridge: t.one('bridgeId'),
    },
  ),
  Direction: t.createEnum(['home', 'foreign']),
  Provider: t.createEnum(['pulsechain', 'tokensex']),
  BridgeSide: t.createTable(
    {
      id: t.hex(),
      chainId: t.bigint(),
      address: t.hex(),
      provider: t.enum('Provider'),
      side: t.enum('Direction'),
    },
    {
      chainId: t.index('chainId'),
    },
  ),
  RequiredSignaturesChanged: t.createTable(
    {
      id: t.hex(),
      bridgeId: t.hex().references('BridgeSide.id'),
      bridge: t.one('bridgeId'),
      value: t.bigint(),
      transactionId: t.hex().references('Transaction.id'),
      transaction: t.one('transactionId'),
      logIndex: t.int(),
    },
    {
      bridgeId: t.index('bridgeId'),
      transactionId: t.index('transactionId'),
    },
  ),
  LatestRequiredSignaturesChanged: t.createTable(
    {
      id: t.hex(), // bridgeId - since it is universal for each side of each bridge pair
      orderId: t.hex().references('RequiredSignaturesChanged.id'),
      order: t.one('orderId'),
    },
    {
      orderId: t.index('orderId'),
    },
  ),
  UserRequestForAffirmation: t.createTable(
    {
      id: t.hex(),
      blockId: t.hex().references('Block.id'),
      transactionId: t.hex().references('Transaction.id'),
      messageHash: t.hex(),
      from: t.hex(),
      to: t.hex(),
      amount: t.bigint(),
      encodedData: t.hex(),
      logIndex: t.int(),
      bridgeId: t.hex().references('BridgeSide.id'),
      originationChainId: t.bigint(),
      destinationChainId: t.bigint(),
      requiredSignatureId: t.hex().references('RequiredSignaturesChanged.id'),
      confirmedSignatures: t.bigint(),
      finishedSigning: t.boolean(),
      signatures: t.many('SignedForAffirmation.userRequestId'),
      orderId: t.hex(),
    },
    {
      blockId: t.index('blockId'),
      transactionId: t.index('transactionId'),
      bridgeId: t.index('bridgeId'),
      requiredSignatureId: t.index('requiredSignatureId'),
      finishedSigning: t.index('finishedSigning'),
      orderId: t.index('orderId'),
    },
  ),
  FeeDirector: t.createTable(
    {
      id: t.hex(),
      userRequestId: t.hex().references('UserRequestForSignature.id'),
      userRequest: t.one('userRequestId'),
      recipient: t.hex(),
      settings: t.bigint(),
      limit: t.bigint(),
      multiplier: t.bigint(),
      feeType: t.string(),
      unwrapped: t.boolean(),
      excludePriority: t.boolean(),
    },
    {
      userRequestId: t.index('userRequestId'),
    },
  ),
  SignedForAffirmation: t.createTable(
    {
      id: t.hex(),
      blockId: t.hex().references('Block.id'),
      block: t.one('blockId'),
      transactionId: t.hex().references('Transaction.id'),
      transaction: t.one('transactionId'),
      messageHash: t.hex(),
      orderId: t.hex(),
      validatorId: t.hex(),
      logIndex: t.int(),
      userRequestId: t.hex().references('UserRequestForAffirmation.id'),
      userRequest: t.one('userRequestId'),
      bridgeId: t.hex().references('BridgeSide.id'),
      bridge: t.one('bridgeId'),
      deliveryId: t.hex().references('AffirmationComplete.id'),
      delivery: t.one('deliveryId'),
    },
    {
      blockId: t.index('blockId'),
      transactionId: t.index('transactionId'),
      messageHash: t.index('messageHash'),
      userRequestId: t.index('userRequestId'),
    },
  ),
  UserRequestForSignature: t.createTable(
    {
      id: t.hex(),
      blockId: t.hex().references('Block.id'),
      block: t.one('blockId'),
      transactionId: t.hex().references('Transaction.id'),
      transaction: t.one('transactionId'),
      orderId: t.hex(),
      messageHash: t.hex(),
      from: t.hex(),
      to: t.hex(),
      amount: t.bigint(),
      encodedData: t.hex(),
      logIndex: t.int(),
      bridgeId: t.hex().references('BridgeSide.id'),
      bridge: t.one('bridgeId'),
      originationChainId: t.bigint(),
      destinationChainId: t.bigint(),
      requiredSignatureId: t.hex().references('RequiredSignaturesChanged.id'),
      requiredSignature: t.one('requiredSignatureId'),
      confirmedSignatures: t.bigint(),
      finishedSigning: t.boolean(),
      signatures: t.many('SignedForUserRequest.userRequestId'),
      feeDirectorId: t.hex().references('FeeDirector.id').optional(),
      feeDirector: t.one('feeDirectorId'),
    },
    {
      blockId: t.index('blockId'),
      transactionId: t.index('transactionId'),
      bridgeId: t.index('bridgeId'),
      requiredSignatureId: t.index('requiredSignatureId'),
      finishedSigning: t.index('finishedSigning'),
      feeDirectorId: t.index('feeDirectorId'),
    },
  ),
  SignedForUserRequest: t.createTable(
    {
      id: t.hex(),
      blockId: t.hex().references('Block.id'),
      block: t.one('blockId'),
      transactionId: t.hex().references('Transaction.id'),
      transaction: t.one('transactionId'),
      messageHash: t.hex(),
      orderId: t.hex(),
      validatorId: t.hex(),
      logIndex: t.int(),
      userRequestId: t.hex().references('UserRequestForSignature.id'),
      userRequest: t.one('userRequestId'),
      deliveryId: t.hex().references('RelayMessage.id'),
      delivery: t.one('deliveryId'),
      bridgeId: t.hex().references('BridgeSide.id'),
      bridge: t.one('bridgeId'),
    },
    {
      blockId: t.index('blockId'),
      transactionId: t.index('transactionId'),
      messageHash: t.index('messageHash'),
      userRequestId: t.index('userRequestId'),
    },
  ),
  ReverseMessageHashBinding: t.createTable(
    {
      id: t.hex(), // messageHash
      userRequestId: t.hex().references('UserRequestForSignature.id'),
      userRequest: t.one('userRequestId'),
      bridgeId: t.hex().references('BridgeSide.id'),
      bridge: t.one('bridgeId'),
    },
    {
      userRequestId: t.index('userRequestId'),
    },
  ),
  RelayMessage: t.createTable(
    {
      id: t.hex(),
      messageHash: t.hex(),
      blockId: t.hex().references('Block.id'),
      block: t.one('blockId'),
      transactionId: t.hex().references('Transaction.id'),
      transaction: t.one('transactionId'),
      orderId: t.hex(),
      deliverer: t.hex(),
      logIndex: t.int(),
      userRequestId: t.hex().references('UserRequestForSignature.id'),
      userRequest: t.one('userRequestId'),
      signatures: t.many('SignedForUserRequest.deliveryId'),
    },
    {
      messageHash: t.index('messageHash'),
      transactionId: t.index('transactionId'),
    },
  ),
  AffirmationComplete: t.createTable(
    {
      id: t.hex(),
      blockId: t.hex().references('Block.id'),
      block: t.one('blockId'),
      messageHash: t.hex(),
      transactionId: t.hex().references('Transaction.id'),
      transaction: t.one('transactionId'),
      orderId: t.hex(),
      deliverer: t.hex(),
      logIndex: t.int(),
      userRequestId: t.hex().references('UserRequestForAffirmation.id'),
      userRequest: t.one('userRequestId'),
      signatures: t.many('SignedForAffirmation.deliveryId'),
    },
    {
      messageHash: t.index('messageHash'),
      transactionId: t.index('transactionId'),
    },
  ),
}))
