/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAMBInformationReceiver,
  IAMBInformationReceiverInterface,
} from "../../../contracts/interfaces/IAMBInformationReceiver";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "messageId",
        type: "bytes32",
      },
      {
        name: "status",
        type: "bool",
      },
      {
        name: "result",
        type: "bytes",
      },
    ],
    name: "onInformationReceived",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAMBInformationReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IAMBInformationReceiverInterface {
    return new Interface(_abi) as IAMBInformationReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAMBInformationReceiver {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAMBInformationReceiver;
  }
}
