/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBridgeValidators,
  IBridgeValidatorsInterface,
} from "../../../contracts/interfaces/IBridgeValidators";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "requiredSignatures",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_validator",
        type: "address",
      },
    ],
    name: "isValidator",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBridgeValidators__factory {
  static readonly abi = _abi;
  static createInterface(): IBridgeValidatorsInterface {
    return new Interface(_abi) as IBridgeValidatorsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBridgeValidators {
    return new Contract(address, _abi, runner) as unknown as IBridgeValidators;
  }
}
