/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IBasicOmnibridgeBNBInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "handleBridgedTokensAndCall"
      | "handleNativeTokensAndCall"
      | "relayTokensAndCall"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "handleBridgedTokensAndCall",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleNativeTokensAndCall",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "relayTokensAndCall",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "handleBridgedTokensAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleNativeTokensAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayTokensAndCall",
    data: BytesLike
  ): Result;
}

export interface IBasicOmnibridgeBNB extends BaseContract {
  connect(runner?: ContractRunner | null): IBasicOmnibridgeBNB;
  waitForDeployment(): Promise<this>;

  interface: IBasicOmnibridgeBNBInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  handleBridgedTokensAndCall: TypedContractMethod<
    [
      _token: AddressLike,
      _recipient: AddressLike,
      _value: BigNumberish,
      _data: BytesLike,
      _senderOrigin: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  handleNativeTokensAndCall: TypedContractMethod<
    [
      _token: AddressLike,
      _recipient: AddressLike,
      _value: BigNumberish,
      _data: BytesLike,
      _senderOrigin: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  relayTokensAndCall: TypedContractMethod<
    [
      token: AddressLike,
      _receiver: AddressLike,
      _value: BigNumberish,
      _data: BytesLike,
      _senderOrigin: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "handleBridgedTokensAndCall"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _recipient: AddressLike,
      _value: BigNumberish,
      _data: BytesLike,
      _senderOrigin: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleNativeTokensAndCall"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _recipient: AddressLike,
      _value: BigNumberish,
      _data: BytesLike,
      _senderOrigin: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "relayTokensAndCall"
  ): TypedContractMethod<
    [
      token: AddressLike,
      _receiver: AddressLike,
      _value: BigNumberish,
      _data: BytesLike,
      _senderOrigin: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
