/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BridgedTokensRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "bridgedTokenAddress" | "nativeTokenAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bridgedTokenAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nativeTokenAddress",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "bridgedTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nativeTokenAddress",
    data: BytesLike
  ): Result;
}

export interface BridgedTokensRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BridgedTokensRegistry;
  waitForDeployment(): Promise<this>;

  interface: BridgedTokensRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bridgedTokenAddress: TypedContractMethod<
    [_nativeToken: AddressLike],
    [string],
    "view"
  >;

  nativeTokenAddress: TypedContractMethod<
    [_bridgedToken: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bridgedTokenAddress"
  ): TypedContractMethod<[_nativeToken: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "nativeTokenAddress"
  ): TypedContractMethod<[_bridgedToken: AddressLike], [string], "view">;

  filters: {};
}
