/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC677__factory } from "./ERC677__factory";
export { LegacyERC20__factory } from "./LegacyERC20__factory";
