/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenOmnibridgeRouter from "./TokenOmnibridgeRouter";
export type { tokenOmnibridgeRouter };
import type * as wethOmnibridgeRouterV2 from "./WETHOmnibridgeRouterV2";
export type { wethOmnibridgeRouterV2 };
