/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  BaseOverdrawManagement,
  BaseOverdrawManagementInterface,
} from "../../../contracts/upgradeable_contracts/BaseOverdrawManagement";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "outOfLimitAmount",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "messageId",
        type: "bytes32",
      },
      {
        name: "unlockOnForeign",
        type: "bool",
      },
      {
        name: "valueToUnlock",
        type: "uint256",
      },
    ],
    name: "fixAssetsAboveLimits",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        name: "value",
        type: "uint256",
      },
      {
        indexed: true,
        name: "messageId",
        type: "bytes32",
      },
    ],
    name: "MediatorAmountLimitExceeded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        name: "value",
        type: "uint256",
      },
      {
        indexed: true,
        name: "transactionHash",
        type: "bytes32",
      },
      {
        indexed: false,
        name: "messageId",
        type: "bytes32",
      },
    ],
    name: "AmountLimitExceeded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "messageId",
        type: "bytes32",
      },
      {
        indexed: false,
        name: "value",
        type: "uint256",
      },
      {
        indexed: false,
        name: "remaining",
        type: "uint256",
      },
    ],
    name: "AssetAboveLimitsFixed",
    type: "event",
  },
] as const;

export class BaseOverdrawManagement__factory {
  static readonly abi = _abi;
  static createInterface(): BaseOverdrawManagementInterface {
    return new Interface(_abi) as BaseOverdrawManagementInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BaseOverdrawManagement {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as BaseOverdrawManagement;
  }
}
