/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBasicAMBMediator,
  IBasicAMBMediatorInterface,
} from "../../../../contracts/routers/WETHOmnibridgeRouterV2/IBasicAMBMediator";

const _abi = [
  {
    inputs: [],
    name: "bridgeContract",
    outputs: [
      {
        internalType: "contract IAMB",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBasicAMBMediator__factory {
  static readonly abi = _abi;
  static createInterface(): IBasicAMBMediatorInterface {
    return new Interface(_abi) as IBasicAMBMediatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBasicAMBMediator {
    return new Contract(address, _abi, runner) as unknown as IBasicAMBMediator;
  }
}
