/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TransientReentrancy,
  TransientReentrancyInterface,
} from "../../../../contracts/routers/WETHOmnibridgeRouterV2/TransientReentrancy";

const _abi = [
  {
    inputs: [],
    name: "ReentrancyGuard",
    type: "error",
  },
] as const;

export class TransientReentrancy__factory {
  static readonly abi = _abi;
  static createInterface(): TransientReentrancyInterface {
    return new Interface(_abi) as TransientReentrancyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TransientReentrancy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TransientReentrancy;
  }
}
